### ISSUE TITLE
req.body

### ISSUE THREAD

**Issue by imaninyasia** [imaninyasia/Mover#2]
i'm trying to get the user sereal primary key so i can add it to another field in the api fetch.
i'm trying to enter user id but i'm not sure how i'd access it.. please help!
function saveRooms(req, res, next){
 db.any(`INSERT INTO rooms (room_id, user_id) VALUES ($1, $2);`,
  [req.body.room, req.body.id])
 .then(()=>{
  console.log('created new room tab')
 })
 .catch(error=> console.log(error))
}
@mgershowitz @gittheking @trevorpreston @irwintsay

**Comment by gittheking** [comment]
@imaninyasia How are you making the call to your server (aka give us a code snippet)? All we're seeing here is the server side code from the model - we need to see more information such as the React Component that is making the fetch call. also, please wrap your code snippets with ` ``` `  so it's easier for us to read.

**Comment by imaninyasia** [comment]
i have a new issue, i have a jwt token in a component in a route, but i'm trying to get it to state in another route. i'm using react router. i have no idea how to do this. @gittheking

**Comment by imaninyasia** [comment]
i'm trying this.props.router and this.props.route, router has a path a could follow, but the first level i need to go into is a function. please help! 
@gittheking @trevorpreston @irwintsay @mgershowitz @jasonseminara

**Comment by ntaft** [comment]
I think I know what you are getting at - returning the unique key that was generated after you insert a new row. If so, add  ```RETURNING id``` to the line should work, e.g. ```INSERT INTO rooms (room_id, user_id) VALUES ($1, $2) RETURNING id```

**Comment by trevorpreston** [comment]
To be queued you need to follow the instructions.

**Comment by trevorpreston** [comment]
https://git.generalassemb.ly/gist/bobbyking/3b7e8d65205a6a0580559cd304e1ce84

**Comment by imaninyasia** [comment]
@ntaft so i'm using jwt, and i'm trying to make a change in the parent's state from the child, and i'm also trying to pass a value from one route to the other. anyone know how to do that? room_id is a static int that's being passed through req.body, and its the user id that i'm trying to store in state, since there is an authenticate function on each fetch to the database which provides res.userData.userID
**react router **passing state value to different route ** altering state from child prop
@gittheking @trevorpreston @irwintsay @mgershowitz @jasonseminara

**Comment by jasonseminara** [comment]
have you looked at this? https://github.com/ReactTraining/react-router/issues/1857
